### ISSUE TITLE
Louvain sous Windows : problème sur la ligne de commande

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#1]
J'écris ici plutôt que de proposer un commit pour que tu puisses voir la solution et tester si ça fonctionne sous Linux.

La ligne de commande de Louvain ne fonctionne pas sous (mon) Windows:

   ` system(command = "bin/LOUVAIN/louvain_win.exe bin/LOUVAIN/net.bin -l -1 -q 0 -c 0.5 -k 1 -w bin/LOUVAIN/net.weights > bin/LOUVAIN/net.tree")`

 et après tests c'est à cause de la spécification du fichier de sortie ` > net.tree`

Si j'essaie depuis l'invite de commande windows cmd, ça fonctionne : 
![image](https://user-images.githubusercontent.com/7148016/128197264-42f217d0-cce6-4fca-bc46-f00844d0c0cf.png)

Par contre depuis R, ça échoue avec l'erreur "More than one file", il semble interpréter le ` > net.tree` comme un nouveau fichier. 
![image](https://user-images.githubusercontent.com/7148016/128197479-3947d60b-a833-4879-b5b3-9fd75d59f479.png)

Il est possible que le `>` soit mal interprété / encodé lors de la communication R/windows?

Comme workaround il est possible de ne pas demander à Louvain de sauver l'output dans un fichier, mais de le sauver dans une variable :

    tree <- system(command = "bin/LOUVAIN/louvain_win.exe bin/LOUVAIN/net.bin -l -1 -q 0 -c 0.5 -k 1 -w bin/LOUVAIN/net.weights",
                   intern = TRUE)

Et ensuite, on écrit l'output sur le disque avec `cat()`
```
cat(tree[1:(length(tree) - 1)],
      file = "bin/LOUVAIN/net.tree",
      sep = "\n")
```

J'ai comparé les outputs entre cette méthode, et l'appel louvain qui avait fonctionné depuis l'invite de commande windows, et les résultats sont identiques, donc ça me parait un workaround satisfaisant si ça fonctionne sur les autres systèmes ?

**Comment by maximelenormand** [comment]
Je viens de faire un commit en ajoutant les lignes sous }else if(os == "Windows"){ car ça bug sous linux

**Comment by Farewe** [comment]
Il restait encore le ` > net.tree`  donc ça ne marchait pas. J'ai fait un commit rapide en déplaçant ce bout là dans le `if(os == "Linux")`

Vérifie que ça fonctionne pour toi avec ce changement !

**Comment by maximelenormand** [comment]
ok merci, c'est tout bon !
