### ISSUE TITLE
Build fail on MacOS

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#11]
Hello,

apparemment le build du package échoue sur Mac OS, et ça semble venir des objets spatiaux / sf / fonction `map_clusters()`:

https://github.com/bioRgeo/bioRgeo/actions/runs/3560293362/jobs/5980224261#step:6:137

Ca fait référence à ce chunk de code pour reproduire le problème : 
https://github.com/bioRgeo/bioRgeo/blob/master/vignettes/a3_2_hierarchical_clustering.Rmd#L388

Quelqu'un a accès à un mac pour essayer de voir ce qui ne marche pas ?

**Comment by pierredenelle** [comment]
Je viens de tester avec une doctorante, qui a la version 12.5.1. Monterey de Mac et le chunk de code vers lequel tu renvoyais a bien tourné.
Je ré-essaierai avec elle Lundi, en tentant de générer la vignette a3_2_hierarchical_clustering.Rmd sur son ordi.

**Comment by pierredenelle** [comment]
J'ai aussi un warning maintenant quand je fais devtools::check(args = "--as-cran") => replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'bioRgeo'

Je vais remplacer toutes les utilisations de reshape2::melt par tidyr::pivot_longer => cette fonction est davantage à jour et en plus ça nous enlève une dépendance (on n'aura plus besoin d'importer le package R reshape2)
