### ISSUE TITLE
OSLOM sous windows, fix pour le faire tourner

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#2]
En ce qui concerne OSLOM sous Windows, j'ai également eu une erreur : OSLOM n'arrive pas à sauver le fichier output. Visiblement c'est parce qu'il n'arrive pas à créer le dossier dans lequel stocker l'output.

J'ai créé manuellement le dossier output et OSLOM fonctionne. Voici un fix pour la fonction : 
Ajouter
`dir.create("bin/OSLOM/net.txt_oslo_files", showWarnings = FALSE)`
ligne 191, après 
`}else if(os == "Windows"){`

```
  }else if(os == "Windows"){
    dir.create("bin/OSLOM/net.txt_oslo_files", showWarnings = FALSE)
    if(directed){
      cmd=paste0("bin/OSLOM/oslom_dir_win.exe ", cmd)
    }else{
      cmd=paste0("bin/OSLOM/oslom_undir_win.exe ", cmd)
    }
```

**Comment by maximelenormand** [comment]
Je viens de faire un commit en ajoutant la ligne
