### ISSUE TITLE
Fichiers temporaires des algorithmes et autorisations Windows

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#3]
Les problèmes d'autorisation pour les fichiers qui peuvent survenir sous Windows sont probablement liés au répertoire dans lequel les données sont stockées temporairement pour faire tourner les algorithmes. Pour le moment les fonctions créent des fichiers temporaires dans le dossier du package, qui lui-même peut être situé dans un chemin pouvant nécessiter des autorisations spéciales (e.g. Program Files). 

Pour éviter les problèmes on devrait peut-être éviter de créer des fichiers temporaires dans le dossier du package, mais plutôt créer un dossier temporaire dans le répertoire de travail directement, par exemple avec une ligne comme ceci en exemple pour `oslom.R` :
`dir.create("bioRgeo_temp/oslom", showWarnings = FALSE, recursive = TRUE)`

On peut ensuite sauver les fichiers dedans avec 
`write.table(netemp, paste0("bioRgeo_temp/oslom/net.txt"), row.names=FALSE, col.names=FALSE, sep=" ")`

Et ensuite, les lignes de commandes seraient à altérer en adaptant le code entre répertoire de la lib et répertoire temporaire avec les données :
```
cmd=paste0("-r ", r, " -hr ", hr, " -seed ", seed," -t ", t, " -cp ", cp)
  if(weight){
    cmd=paste0("-f ", current_path, "/bioRgeo_temp/oslom/net.txt -w", cmd)
  }else{
    cmd=paste0("-f ", current_path, "/bioRgeo_temp/oslom/net.txt -uw ", cmd)
  }

  if(os == "Linux"){
    if(directed){
      cmd=paste0(biodir, "/bin/OSLOM/oslom_dir_lin ", cmd)
    }else{
      cmd=paste0(biodir, "/bin/OSLOM/oslom_undir_lin ", cmd)
    }
  }else if(os == "Windows"){
    dir.create("bioRgeo_temp/oslom/net.txt_oslo_files", showWarnings = FALSE)
    if(directed){
      cmd=paste0(biodir, "/bin/OSLOM/oslom_dir_win.exe ", cmd)
    }else{
      cmd=paste0(biodir, "/bin/OSLOM/oslom_undir_win.exe ", cmd)
    }
  }else if(os == "Darwin"){
    stop("TO IMPLEMENT")
  }else{
    stop("Linux, Windows or Mac distributions only.")
  }
```
C'est un essai de modif rapide que j'ai fait ici, je ne l'ai pas vraiment testé ou modifié jusqu'au bout. A la fin on peut soit vider le répertoire temporaire (avec `unlink`), soit le laisser tel quel (à la biomod). Qu'en penses-tu ?

**Comment by maximelenormand** [comment]
C'est une bonne idée, j'ai mis à jour oslom, dis moi si ça tourne chez toi. On pourra ajouter un argument delete_temp=TRUE pour laisser la possibilité à l'utilisateur de vérifier les sorties brutes. On pourrait même donner la possibilité de nommer et choisir l'emplacement du dossier temporaire pour faire tourner les fonctions en parallèle par exemple...

**Comment by Farewe** [comment]
Ca fonctionne nickel pour oslom.

Bonne idée de choisir l'emplacement temporaire pour la parallélisation oui, ça me parait bien !

**Comment by maximelenormand** [comment]
Je viens de mettre à jour oslom avec les deux nouveaux arguments. J'ai opté pour un folder "oslom_temp" créé dans le wd par défaut pour éviter la création d'une arborescence. Cela permet de faciliter la suppression pour les utilisateurs que ne veulent pas voir trainer de dossier temporaire, à discuter...

**Comment by maximelenormand** [comment]
J'ai mis à jour infomap et louvain en suivant le même principe

**Comment by maximelenormand** [comment]
Il y a l'erreur (Warning: the condition has length > 1 and only the first element will be used) qui est apparue dans la génération automatique de l'aide (avec l'exemple) pour oslom et louvain (et probablement infomap car j'ai supprimé les warnings pour tidyr). Cette erreur n'apparait pas sous linux, tiens moi au courant si elle apparait sous windows et que tu arrives à l'identifier. Je vais vérifier mes codes en attendant.

**Comment by Farewe** [comment]
Quand je teste les fonctions manuellement ça semble ok pour le moment, mais je n'ai pas été plus loin que des tests simples. 
Je n'arrive plus à compiler le package ce soir, j'ai une erreur qui survient et qui semble provenir des éléments Rcpp. 

J'ai fait un commit avec pas mal de modifs en parallèle de tes modifs (il n'y a pas eu de conflit à gérer, j'ai travaillé sur spproject et 2 nouvelles fonctions), mais je n'ai pas pu recompiler et réinstaller le package pour le moment, donc il peut rester des soucis dans ce que j'ai préparé. Je vais le push dans pas très longtemps.

**Comment by Farewe** [comment]
Oui désolé je l'avais pas mis dans le répertoire 'test'. C'est corrigé  ;)
