### ISSUE TITLE
Propositions de logo pour bioRgeo

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#4]
Quelques propositions de logo faites par Sarah, sur la base des hexagones du tidyverse : 

Logo 1
![logo1](https://user-images.githubusercontent.com/7148016/128994979-b4003ecc-3175-4b70-800c-dfa7c9bc8459.png)

Logo 2
![logo2](https://user-images.githubusercontent.com/7148016/128994987-84bf91f6-c35e-43aa-a8f5-b5e86e49f0b3.png)

Logo 3
![logo3](https://user-images.githubusercontent.com/7148016/128994992-1ffc2b14-ec24-4007-ab68-d7e67e4e6085.png)

Lequel tu préfères ?

N'hésite pas à faire des commentaires ou suggestions ou des recommandations pour les couleurs notamment. J'ai les version SVG également si tu veux les retravailler !

**Comment by maximelenormand** [comment]
Ils sont superbes ! Beau boulot ! J'ai un faible pour le 2 mais le 1 est super également !

**Comment by Farewe** [comment]
Moi aussi j'ai une préférence pour le second, car il suggère différentes biorégions (nuances de turquoise) détectées par les noeuds (zone turquoise claire identifiée avec les noeuds oranges vs. zone turquoise foncée identifiée par les noeuds jaunes). 

Si t'es ok au niveau des couleurs je te mets les fichiers source en pièce jointe ici, et si tu veux des modifs n'hésite pas, je passerai le message. 


[bioRgeo_logo.zip](https://github.com/bioRgeo/bioRgeo/files/6968180/bioRgeo_logo.zip)

**Comment by pierredenelle** [comment]
Excellent!
Le 2 était aussi mon préféré.

Au passage, j'avais vu récemment qu'il existait un package R pour formatter
les logos. Voici quelques ressources liées aux logos de package (le dernier
lien est une exemple) :
https://www.rstudio.com/about/logos/
https://github.com/rstudio/hex-stickers/
https://usethis.r-lib.org/reference/use_logo.html
https://shixiangwang.github.io/home/en/post/2019-06-20-how-i-create-ucscxenatools-logo/

A plus,
Pierre
