### ISSUE TITLE
NAMESPACE généré manuellement

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#5]
Roxygen m'indique que le NAMESPACE a été généré manuellement et ne sera pas modifié par roxygen. D'expérience le NAMESPACE est un fichier assez problématique à générer, roxygen facilite beaucoup la tâche en l'automatisant. Y a-t-il un besoin particulier qui nécessite la génération manuelle du NAMESPACE ou peut-on envisager d'utiliser l'automatisation par roxygen?

**Comment by maximelenormand** [comment]
Oui c'est parceque j'ai ajouté les lignes 

importFrom(Rcpp, evalCpp)
importFrom(Rdpack,reprompt)

manuellement pour faire un package Rcpp (https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-package.pdf) 

à voir si roxygen peut prendre ça ne compte automatiquement...

**Comment by Farewe** [comment]
Ok je comprends. Normalement roxygen2 doit pouvoir le faire oui je pense : https://www.r-bloggers.com/2016/08/rcpp-and-roxygen2/

Il faut déplacer le importFrom dans la doc roxygen2 du package, dans un fichier package.R :
```
#' your_package
#' 
#' Description of your package
#' 
#' @docType package
#' @author you <youremail>
#' @import Rcpp another_package another
#' @importFrom Rcpp evalCpp
#' @useDynLib your_package
#' @name your_package
NULL  
```

On doit pouvoir y rajouter 
`#' @importFrom Rdpack reprompt`

**Comment by maximelenormand** [comment]
Ok ça marche, je te laisse géré ça (?). Tu as réussi à installer le package du coup ?

**Comment by Farewe** [comment]
Normalement j'ai fait la migration vers roxygen2, ça semble fonctionner, je te laisse vérifier que tout est ok pour toi ?

J'ai supprimé les importations de packages qui ne semblaient pas utilisés après recherche dans le code R : 
**ade4, DescTools, lctools, Rdpack, SMUT**

S'ils sont effectivement utilisés, il faudra les remettre dans `package.R` à la ligne 

`#' @import Rcpp cluster dplyr fastcluster RcppEigen`

J'ai supprimé aussi l'importation de `reprompt` depuis `Rdpack` car je n'ai pas vu son utilité dans le package, c'est probablement une ancienne utilisation dans la version de Pierre ?
Si c'est une erreur, remettre 
`#' @importFrom Rdpack reprompt`
dans `package.R`

Faut-il documenter les fonctions en c++ (abc, prodmat) ou bien les laisse-t-on en interne ?

**Comment by Farewe** [comment]
Si on valide la suppression des packages **ade4, DescTools, lctools, Rdpack, SMUT** dans `NAMESPACE`, il faudra aussi les enlever de `DESCRIPTION`.

**Comment by Farewe** [comment]
> 
> 
> Ok je m'occupe de ça oui ! Je te préviendrai en cas de pépin.
> 
> Pour le package, oui c'est installé, par contre la fonction abc() ne marche plus désormais (je vais ouvrir une autre issue, pas encore eu le temps de regarder ce qui ne fonctionne pas).

J'ai recompilé le package en nettoyant tout les fichiers générés précédemment et c'est ok maintenant, plus d'erreur de mon côté !

**Comment by maximelenormand** [comment]
Pareil pour moi tout tourne nickel

**Comment by maximelenormand** [comment]
Je serai d'avis de laisser abc et prodmat en interne mais si tu penses que ça peut être utile dans le cadre du package on peut les documenter. 

Je vais faire le point sur les packages et essayer de comprendre la différence entre NAMESPACE et DESCRIPTION

**Comment by Farewe** [comment]
Le fichier DESCRIPTION sera surtout utilisé par le CRAN, et il faudra qu'il soit irréprochable sinon ce sera refoulé direct. Tant qu'on fonctionne hors CRAN on peut se permettre des petits soucis dans ce fichier, mais c'est mieux d'être clean dès que possible pour éviter une dette de code qui sera chiante à gérer lors de la préparation de la soumission CRAN ;)

C'est surtout [cette section sur les dépendances qui va poser problème dans DESCRIPTION](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies), qui est en général dure à gérer. Pour vérifier que c'est ok [il faut faire un check du package](https://r-pkgs.org/r-cmd-check.html) avec les arguments --as-cran. Il faut régler absolument tous les soucis qui sont mentionnés, que ce soit des erreurs, warnings ou notes, sinon le package sera refusé. 

Le plus tôt on le fait, et on fixe les problèmes, le mieux ce sera. Perso j'ai toujours attendu le moment de soumettre pour le faire et il faut replonger dans tout le code, ce que je regrette sur le coup ;)

**Important :** Pour fixer tous les problèmes il faudra probablement régler les appels de fonctions issus de packages externes. Il va probablement falloir réécrire la plupart au format `package::fonction()` au lieu de `fonction()`

**Comment by maximelenormand** [comment]
Bon bah on est pas mal au niveau du check. Il faudra automatiser tout ça avec github actions pour faire les checks et la construction du site à chaque modif du master.
