### ISSUE TITLE
Liste des éléments à fixer pour passer avec succès le premier R CMD CHECK complet

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#6]
- [x] Vérifier toutes les fonctions extérieures pour les réécrire en `package::fonction()`
- [x] Décider quels packages ont vraiment besoin d'être importés en entier pour limiter les conflits (actuellement tous les packages à importer ne sont pas importés, et il y a des conflits dans les fonctions, e.g. entre igraph et dplyr)
- [x] Rendre les scripts dans le dossier tests exécutables en stand-alone
- [x] Ajouter dans `.Rbuildignore` tout ce qui doit être exclu de la compilation (notamment les exécutables ? Les dll pour Windows ? pkgdown etc.)

(A compléter !)

**Comment by maximelenormand** [comment]
A priori on passe le premier check, j'ai retravaillé les data, il fallait les séparer (un rda par objet), les compresser en bzip2 et ajouter un fichier R/data.R pour la documentation (à rédiger, template pour l'instant).

Pas de warning pour les packages mais il va falloir bien vérifier les imports et mettre à jour tous les fichiers associés au info sur les packages.

**Comment by maximelenormand** [comment]
C'est du détail mais il faudrait essayer de séparer les fonctions des données dans l'onglet références du site, il font ça pour ggplot2 https://ggplot2.tidyverse.org/reference/index.html et ça rend vraiment bien.

**Comment by maximelenormand** [comment]
Par contre avec les exécutables dans le .Rbuildignore on ne peut plus utiliser toutes les fonctions après installation du package mais en copiant/collant le bin dans le fichier bioRgeo en local ça fonctionne parfaitement. On pourrait carrément créer un bin.zip, le télécharger et le dézipper dans bioRgeo lors de la première utilisation de louvain, oslom ou infomap si l'utilisateur est ok.

**Comment by maximelenormand** [comment]
J'ai ajouté des sections pour l'onglet référence du site (il suffit juste de modifier le fichier _pkgdown.yml manuellement).

J'ai créé une fonction bin() pour télécharger et dézipper le dossier bin dans un dossier choisi par l'utilisateur (bioRgeo par défaut). J'ai mis à jour infomap, oslom et louvain pour offrir la possibilité de définir le chemin vers "bin". J'ai réussi à gérer les permissions pour linux mais je n'ai rien fait pour windows pour l'instant. A voir si tout ça fonctionne... Il faudra faire une vignette dédiée.

**Comment by Farewe** [comment]
Ok ça marche, je vais regarder ça dès que je peux (je peux pas le faire pour le moment car je suis pris par d'autres tâches urgentes). 

Il faudra probablement englober nos exemples avec les binaires avec `\donttest{}` pour passer le CRAN check ([voir un exemple ici](https://github.com/Farewe/invacost/blob/master/R/modelcosts.R#L102)).

**Comment by maximelenormand** [comment]
Ok, pas de soucis. J'ai fait un peu de ménage dans les packages (package.R pour NAMESPACE, DESCRIPTION et README) à voir si je n'ai pas fait de connerie. J'ai viré les imports et importsfrom de package.R car on utilise systématiquement :: mais je suis pas sur et certain. En tout cas je passe le devtools::check() sur mon ordi.

J'ai mis les exemples et les exécutables dans le Rgitignore pour l'instant.

**Comment by maximelenormand** [comment]
Ok, pas de soucis. J'ai fait un peu de ménage dans les packages (package.R pour NAMESPACE, DESCRIPTION et README) à voir si je n'ai pas fait de connerie. J'ai viré les imports et importsfrom de package.R car on utilise systématiquement :: mais je suis pas sur et certain. En tout cas je passe le devtools::check() sur mon ordi.

J'ai mis les exemples et les exécutables dans le Rgitignore pour l'instant.

**Comment by maximelenormand** [comment]
J'ai automatiser la création du site et le R CMD CHECK via GitHub Actions. Tout roule.
