### ISSUE TITLE
Optimisation de `spproject`

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#7]
J'ai comparé la performance de `spproject` avec les fonctions d'autres packages qui ont le même objectif, et la performance de `spproject` est assez bonne en fait, il n'y a que `designdist` du package `vegan` qui est plus rapide et plus efficace. 
![image](https://user-images.githubusercontent.com/7148016/131094499-3eb0af5e-38a9-4f9e-a0b6-122507017b4e.png)
L'axe x sur le graphe est la taille de la matrice de co-occurrence (matrice carrée).

Je me demandais si on ne pouvait pas essayer d'optimiser `spproject` pour atteindre les performances de `vegdist`? L'un des gros intérêts de `vegdist` également est de pouvoir calculer la distance que l'on souhaite (l'utilisateur rentre une formule en fonction de A, B, J), est-ce que l'on ne ferait pas pareil ici, en acceptant les formules libres ?

Enfin, sur mon pc avec 32Gb de RAM aucune fonction n'a pu fonctionner pour des distances de matrices delà d'une certaine taille (50 000 * 50 000 de mémoire). Je ne sais pas si on peut envisager dans le futur de créer une version "memory-safe" qui décompose la matrice en plus petits éléments pour pouvoir l'appliquer sur des grandes matrices de co-occurrence.

Ci-dessous mon code pour comparer la performance des algos, nécessite `vegan`, `betapart`, `simba` (mais en réalité le vraie duel est uniquement entre `vegan` et `bioRgeo`).

```
library(bioRgeo)
library(ggplot2)


res <- NULL
for(dimstot in c(100, 1e3, 2e3, 3e3, 4e3, 5e3, 1e4))#, 2e4, 3e4, 5e4))
{
  cat(paste(Sys.time(), dimstot, "\n"))
  comat <- matrix(sample(0:1000, size = dimstot^2, replace = TRUE, prob = 1/(1:1001)^3), dimstot, dimstot)
  rownames(comat) <- paste0("Site", 1:dimstot)
  colnames(comat) <- paste0("Species", 1:dimstot)
  # rich <- rowSums(comat)
  # hist(rich)
  # occ <- colSums(comat)
  # hist(occ)

  cat("Occurrence\n")
  # Occurrence
  cat(" - spproject ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "spproject",
                          metric = "jaccard",
                          matrix(as.vector(system.time(spproject(comat, metric = "Jaccard")))[1:3], nr = 1)))
  if(dimstot <= 3e3)
  {
    cat(" - vegdist ...\n")
    res <- rbind(res,
                 data.frame(dimstot = dimstot,
                            method = "vegdist",
                            metric = "jaccard",
                            matrix(as.vector(system.time(vegan::vegdist(comat, metric = "jaccard")))[1:3], nr = 1)))
  }
  cat(" - designdist ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "designdist",
                          metric = "jaccard",
                          matrix(as.vector(system.time(vegan::designdist(comat, "(A+B-2*J)/(A+B-J)", terms = "binary")))[1:3], nr = 1)))

  comatocc <- comat
  comatocc[comatocc > 0] <- 1
  cat(" - betapart ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "betapart",
                          metric = "jaccard",
                          matrix(as.vector(system.time(betapart::beta.multi(comatocc, index.family = "jaccard")))[1:3], nr = 1)))


  cat(" - ade4 ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "simba",
                          metric = "jaccard",
                          matrix(as.vector(system.time(simba::sim(comat, method = "jaccard")))[1:3], nr = 1)))



  cat("Abundance\n")
  # Abundance
  cat(" - spproject ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "spproject",
                          metric = "bray",
                          matrix(as.vector(system.time(spproject(comat, metric = "Bray")))[1:3], nr = 1)))
  if(dimstot <= 3e3)
  {
    cat(" - vegdist ...\n")
    res <- rbind(res,
                 data.frame(dimstot = dimstot,
                            method = "vegdist",
                            metric = "bray",
                            matrix(as.vector(system.time(vegan::vegdist(comat, metric = "bray")))[1:3], nr = 1)))
  }
  cat(" - designdist ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "designdist",
                          metric = "bray",
                          matrix(as.vector(system.time(vegan::designdist(comat, "(A+B-2*J)/(A+B)", terms = "minimum")))[1:3], nr = 1)))
  if(dimstot <= 3e3)
  {
  cat(" - betapart ...\n")
  res <- rbind(res,
               data.frame(dimstot = dimstot,
                          method = "betapart",
                          metric = "bray",
                          matrix(as.vector(system.time(betapart::beta.pair.abund(comat, index.family = "bray")))[1:3], nr = 1)))
  }
}


ggplot(res,
       aes(x = dimstot,
           y = X3,
           col = method)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ metric, scales = "free_y")

```

**Comment by maximelenormand** [comment]
J'ai jeté un œil au code de designdist, c'est le même genre de code que le notre (produit matriciel pour les occurrences et boucles pour les abondances). Ils utilisent du fortran pour le produit matriciel avec tcrossprod du package Matrix, ça va un poil plus vite qu'avec prodmat (à voir si on change). Pour les boucles ils utilisent comme nous du cpp. La grosse différence vient du format matriciel pour eux (plus simple à gérer mais une seule matrice en sortie) et en colonne pour nous (nécessite des opérations de transformation mais plusieurs métriques en sortie et surtout la possibilité de calculer abc et ABC une bonne fois pour toute...). On pourrait imaginer pouvoir sortir une liste de matrices mais ça serait volumineux et pas vraiment adapté à la suite de notre code.

On peut facilement ajouter un argument formula pour calculer des formules libres contenant les éléments abc et/ou ABC. 

Pour le coté memory-safe on peut y réfléchir mais je crains que le vrai problème ne vienne pas des opérations mais de la duplication de très grande matrice en sortie...

On peut se faire une visio dans la semaine pour discuter de tout ça.

**Comment by maximelenormand** [comment]
J'ai fait tourner deux tests après avoir optimisé un peu spproject (utilisation de tcrossprod au lieu de prodmat et j'ai supprimé une étape d'initialisation inutile) mais ça ne change pas grand chose, on reste dans les mêmes ordres de grandeur que designdist mais on est moins performant à cause du format colonne je pense, on pourra se pencher là-dessus plus tard si on est motivé...  

Je vais ajouter un argument 'formula' et implémenter le calcul de métrique sur mesure demain je pense.

![Test1](https://user-images.githubusercontent.com/12052066/131570839-1dc75914-6147-41ec-ad88-f26a489e5fac.png)
![Test2](https://user-images.githubusercontent.com/12052066/131570847-a78a4de6-00f3-4893-9526-dcf802e4b783.png)

**Comment by maximelenormand** [comment]
Je viens de mettre à jour spproject avec l'ajout de l’argument formula. Tout semble ok.
