### ISSUE TITLE
Problème avec l'objet dist.obj dans clustering_hierarchical

### ISSUE THREAD

**Issue by maximelenormand** [bioRgeo/bioRgeo#8]
J'ai regardé un peu le passage de "distances" à "dist.obj" dans clustering_hierarchical. J'ai retravaillé la fonction df_to_contingency pour pouvoir faire des matrices carrés symétriques en pensant que le problème venait de là mais je me suis aperçu qu'il y avait un problème avec la fonction interne .dfToDist. 

Ce serait mieux d'utiliser la fonction df_to_contingency. Il faudra voir si tout est ok, j'ai ajouté une ligne commenté (ligne 175) pour que tu puisses faire des tests.

**Comment by Farewe** [comment]
Ok vu, je vais jeter un oeil à ça dès que possible. J'ai commencé à reprendre / améliorer les fonctions, je vais continuer sur tout le mois de janvier

**Comment by Farewe** [comment]
Après vérification, c'est ok ça fonctionne !

Je vais continuer de tester avec différents datasets mais ça devrait être bon donc je clos l'issue pour le moment.
