### ISSUE TITLE
Test de nombre entier dans la fonction controls

### ISSUE THREAD

**Issue by Farewe** [bioRgeo/bioRgeo#9]
J'ai vu qu'il y avait un test de nombre entier dans la fonction `controls()` :

https://github.com/bioRgeo/bioRgeo/blob/c5853979c0d563afb9169e3041ba52fdbff8202a/R/utils.R#L24

Mais la commande `class(x) == "integer"` ne fonctionne pas pour tester si le nombre est entier : 

```
> class(2) == "integer"
[1] FALSE
````

Pour tester les nombres entiers il vaut mieux utiliser `x %% 1 == 0` ([cf ici](https://stackoverflow.com/questions/3476782/check-if-the-number-is-integer))

Mais je crois que le but ici était juste de s'assurer que l'on a bien quelque chose de numérique ? 

Dans ce cas la commande `is.numeric()` devrait suffire : 
```
> class(2) == "integer"
[1] FALSE
> class(2) == "numeric"
[1] TRUE
> class(2L) == "integer"
[1] TRUE
> class(2L) == "numeric"
[1] FALSE
> is.numeric(2L)
[1] TRUE
> is.numeric(2)
[1] TRUE
```
Donc remplacer la ligne par 
```
if(!is.numeric(X[,3])){
```

Oui je sais, tout ça pour ça ... =)

**Comment by maximelenormand** [comment]
C'est bon j'ai corrigé le problème dans toutes les fonctions. J'ai commenté la fonction controls() qui est en développement, pas sur qu'on l'utilise en fait...
